### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by AmingWu** [orrzohar/PROB#1]
Thanks for releasing the code. How long does your model need to train?

**Comment by orrzohar** [comment]
Hi Aming,
This greatly depends on which dataset you are training on, as for each one of the tasks, there is a varying number of images (which affects training time) and which/how many GPUs you use.

I trained on GCP instances with four 40GB A100 GPUs. Training for T1 was _always_ the longest, with 7h 40m for MOWODB and 1d 15h 41m for SOWODB. This is because I trained for more epochs on T1 than on T2-T4. For example, on SOWODB, for T1-T4, runtimes were 1d 15h 41m, 4h 52m, 3h 36m,  and 3h 30m, respectively. 

I hope this gives you a good sense of the different training times to expect from PROB - broadly speaking, I expect similar training and inference times to that of deformable DETR's. 

Best,
Orr
