### ISSUE TITLE
code running problem

### ISSUE THREAD

**Issue by qwe986050091** [orrzohar/PROB#18]
I try to run the code, but after I choose the wandb command, the program is stuck. I also see the GPU and CPU and find that they are not working. The result can be seen below:
![fbcec54b499d08ed1359d731207660f](https://user-images.githubusercontent.com/117260358/231097265-7a261277-34f6-4003-a057-ee0bb36242aa.png)

**Comment by orrzohar** [comment]
Hi @qwe986050091,

Yes, this is because the program crashed. To use [wandb](https://wandb.ai/), you need to: 

1. create a W&B account.
2. log into your account in the terminal. 

If you prefer not to use wandb, you need to set wandb_project to ""
https://github.com/orrzohar/PROB/blob/09d814353933f8bdfe944c8afd4b57b8416ebc8e/main_open_world.py#L144

also, please uncomment lines 169 and 170 in main_open_world.py

I personally always used wandb, but this should work as well. 

Best,
Orr

**Comment by qwe986050091** [comment]
Thanks for your reply!
