### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Millielele** [orrzohar/PROB#2]
Hello, thanks for your wonderful works!
When I run run.sh, I encounter this problem: 
No such file or directory: './data/OWOD/ImageSets/TOWOD/PROB_V1/learned_owod_t4_ft.txt'
and
subprocess.CalledProcessError: Command '['./configs/M_OWOD_BENCHMARK.sh']' returned non-zero exit status 1.
How to solve these problem?

**Comment by orrzohar** [comment]
Hi @Millielele,
The short explanation: the file you referenced should be created during training. **For some reason, you had a different error in training (probably in T1) that stopped training. Could you find that and send it here?**

The long explanation:
The 'M_OWOD_BENCHMARK' bash file runs the full training pipeline, and in it, it runs each section of the training protocol (training on T1, training on T2, Finetuning... etc.). To enable the best reproducibility, I save the list of image exemplars under the 'ImageSets' directory under the subdir 'exp name / model name' or 'TOWOD/PROB_V1' here. You most likely had an error earlier (probably already in T1) that stopped training, and you only see this because the bash script, after running into that bug, would continue directly to the next command. The last command needs the 'learned_owod_t4_ft' file, which should be created during training, to perform fine-tuning. If you can find the original error, I can help you debug this. 

Best,
Orr

**Comment by orrzohar** [comment]
Hi @Millielele,
It seems like you solved the issue. If that is the
