### ISSUE TITLE
evaluation criteria

### ISSUE THREAD

**Issue by Rzx520** [orrzohar/PROB#30]
I would like to know your evaluation criteria? When you predict 100 targets, and each one of them has an IoU > 0.5 with GT, it means the prediction is correct. Otherwise, it means the prediction is incorrect. Is this understanding?

**Comment by orrzohar** [comment]
Hi @Rzx520,

For an in-detail description on how mAP and Recall are calculated, I suggest [this](https://learnopencv.com/mean-average-precision-map-object-detection-model-evaluation-metric/#How-to-calculate-Average-Precision-(AP)-manually?) resource.

In general, I make 100 predictions per image, and cycle through the entire eval set. For each object class, I sort the predictions in terms of confidence. For each prediction, if it has an IoU>0.5 with a GT annotation, that means the prediction is indeed correct. Otherwise, it is incorrect, as you stated. 

To get the final mAP, we average over all the known (or separated into prev/cur known) classes. 

This means that if you make the right prediction with higher confidence, you won't be penalized by making "wrong" predictions with lower confidence. 

The code implementation of this can be found here:

https://github.com/orrzohar/PROB/blob/10b6518f90495e07b7baf0d1bfa353f0e583eb8e/datasets/open_world_eval.py#L288-L288

Best, 
Orr

**Comment by Rzx520** [comment]
I have a question, will there be many duplicate predictions (and this prediction is correct, IoU>0.5) among the 100 predictions you made for one image, with a high degree of overlap? Will this seriously affect your evaluation?@orrzohar

**Comment by orrzohar** [comment]
HI @Rzx520,
Yeah, this should affect mAP, especially if there is one object with a lot of overlapping predictions with higher confidence than all the other known instances of that object class in the image (remember, mAP is first calculated per class).

If the confidence is similar for all the instances of that object class, then this should not affect the mAP too severely. This was actually a big issue in OW-DETR, but PROB does seem to make less overlapping predictions from what I remember. 

In the end though, while it is of course unwanted, it is hard to say how much it will actually affect evaulation without trying to see how this affects mAP quantitatively.

**Comment by Rzx520** [comment]
Why 'the confidence is similar for all the instances of that object class,  this should not affect the mAP too severely'?@orrzohar
