### ISSUE TITLE
Output are not saved in `/exps/MOWODB/PROB/eval`

### ISSUE THREAD

**Issue by fairoza-corpy** [orrzohar/PROB#46]
I ran the `.run_eval.sh` after solving errors on shared memory, integer error in `open_world_eval.py`, the predictions results was displayed in the terminal, but not saved in the `/exps/MOWODB/PROB/eval` folder. Can someone help me on this?

**Comment by orrzohar** [comment]
Hi @fairoza-corpy,
There should not be any shared memory errors/integer errors. What were they caused by?

And the results should not be saved to ```/exps/MOWODB/PROB/eval``` when running in eval mode. If you want to add that to your script you can add something along this:
https://github.com/orrzohar/PROB/blob/10b6518f90495e07b7baf0d1bfa353f0e583eb8e/main_open_world.py#L364-L371
after this line:
https://github.com/orrzohar/PROB/blob/10b6518f90495e07b7baf0d1bfa353f0e583eb8e/main_open_world.py#L276


You would, of course, need to remove the "train_stats" from that dict and add to the log. Alternitively, you can just save all the output from the terminal using the normal syntax (.run_eval.sh >> log.txt). 

Best,
Orr

**Comment by fairoza-corpy** [comment]
Thank you @orrzohar for your reply. I managed to save the output. I found big differences between the results in the paper and the one that I reproduced. Is it because of hardware issue? Different GPUs?

**Comment by orrzohar** [comment]
Hi @fairoza-corpy,

Perhaps because of the code you edited? You should not have needed to edit
anything

Several people have reproduced our results on different machine with
minimal variation in performance (+- 0.2 mAP/UR) so I doubt that there is
an issue with the codebase.

What batch size are you using? What gpu?

Best,
Orr

**Comment by fairoza-corpy** [comment]
Errors that I was found while running the `./run_eval.sh`:

```
  File "/usr/src/app/datasets/open_world_eval.py", line 279, in parse_rec
    obj_struct['bbox'] = [int(bbox.find('xmin').text),
ValueError: invalid literal for int() with base 10: '204.01'
```

Then, I edited below lines and it works
```
obj_struct['bbox'] = [int(float(bbox.find('xmin').text)),
                              int(float(bbox.find('ymin').text)),
                              int(float(bbox.find('xmax').text)),
                              int(float(bbox.find('ymax').text))]
```
Then, `np.bool` was a deprecated alias for the builtin `bool`. So replaced "/usr/src/app/datasets/open_world_eval.py", line 370 with `bool` only.

The output is reproduced by using Tesla V100 DGXS 32GB, Python 3.8.13, PyTorch 1.11 and CUDA 11.3. 
I have arranged the data according to your instruction but since your link to Pascal VOC dataset require days to download, I downloaded the data from https://www.kaggle.com/datasets/zaraks/pascal-voc-2007 and https://www.kaggle.com/datasets/gopalbhattrai/pascal-voc-2012-dataset.

Below the results that reproduced
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-6f369aa7-7fff-879b-1d07-9c3192f55b13">

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-e446b8fc-7fff-0d40-b7f4-1d78454bde1e">

  | T1 Ours | T1 Paper | T1 Ours | T1 Paper | T1 Ours | T1 Paper | T1 Ours | T1 Paper
-- | -- | -- | -- | -- | -- | -- | -- | --
U-Recall | 27.0710 | 19.4 | 21.9466 | 17.4 | 23.5129 | 19.6 | N/A | N/A
Previously Known mAP | N/A | N/A | 57.7484 | 55.7 | 41.0203 | 43.0 | 28.7372 | 35.7
Current Known mAP | 63.2507 | 59.5 | 26.2052 | 32.2 | 6.4874 | 22.2 | 13.5044 | 18.9
Both mAP | N/A | N/A | 41.9768 | 44.0 | 29.5093 | 36.0 | 24.929 | 31.5

</b>

</b>

Can help me to clarify why there's big difference with the results?

I also found that for MOWODB: t1 ran once, t2 ran once, t3 ran twice, t4 ran once. Can help to explain this as well?

Your paper is very interesting and I would like to understand further.
Thank you for your time and explanation.

Best regards,
Fairoza

**Comment by orrzohar** [comment]
Hi @fairoza-corpy,

I have no idea. It is also very concerning that you have some evaluations running multiple times, as the bash script you are running with run_eval.sh is:

```
echo running eval of prob-detr, M-OWODB dataset

set -x

EXP_DIR=exps/MOWODB/PROB
PY_ARGS=${@:1}
WANDB_NAME=PROB_V1
 
    
PY_ARGS=${@:1}
python -u main_open_world.py \
    --output_dir "${EXP_DIR}/eval" --dataset TOWOD --PREV_INTRODUCED_CLS 0 --CUR_INTRODUCED_CLS 20 \
    --train_set "owod_t1_train" --test_set 'owod_all_task_test' --epochs 191 --lr_drop 35\
    --model_type 'prob' --obj_loss_coef 8e-4 --obj_temp 1.3\
    --pretrain "${EXP_DIR}/t1.pth" --eval --wandb_project ""\
    ${PY_ARGS}
    
    
PY_ARGS=${@:1}
python -u main_open_world.py \
    --output_dir "${EXP_DIR}/eval" --dataset TOWOD --PREV_INTRODUCED_CLS 20 --CUR_INTRODUCED_CLS 20 \
    --train_set "owod_t1_train" --test_set 'owod_all_task_test' --epochs 191 --lr_drop 35\
    --model_type 'prob' --obj_loss_coef 8e-4 --obj_temp 1.3\
    --pretrain "${EXP_DIR}/t2.pth" --eval --wandb_project ""\
    ${PY_ARGS}
    
    
PY_ARGS=${@:1}
python -u main_open_world.py \
    --output_dir "${EXP_DIR}/eval" --dataset TOWOD --PREV_INTRODUCED_CLS 40 --CUR_INTRODUCED_CLS 20 \
    --train_set "owod_t1_train" --test_set 'owod_all_task_test' --epochs 191 --lr_drop 35\
    --model_type 'prob' --obj_loss_coef 8e-4 --obj_temp 1.3\
    --pretrain "${EXP_DIR}/t3.pth" --eval --wandb_project ""\
    ${PY_ARGS}
    
    
PY_ARGS=${@:1}
python -u main_open_world.py \
    --output_dir "${EXP_DIR}/eval" --dataset TOWOD --PREV_INTRODUCED_CLS 60 --CUR_INTRODUCED_CLS 20 \
    --train_set "owod_t1_train" --test_set 'owod_all_task_test' --epochs 191 --lr_drop 35\
    --model_type 'prob' --obj_loss_coef 8e-4 --obj_temp 1.3\
    --pretrain "${EXP_DIR}/t4.pth" --eval --wandb_project ""\
    ${PY_ARGS}
```

So there is no reason why you would run evaluations multiple times. 

I am trying to understand why your annotations are not integers. Maybe it's because you downloaded the dataset from Kaggle instead of the official database. How certain are you that they are the same? Also, there is no reason it should take several days to download the dataset. It took ~30min when I did it. 

I would start by running on a single GPU if I were you. Try to run the original codebase without editing, as you may be masking installation issues. Re the deprecation of np.bool -- this should be just a deprecation warning, and should not stop the running of the script, but `bool` should have the same functionality anyway.

As a whole, the model is more biased towards detecting unknown objects for whatever reasons, but this is very strange as you used the released weights, right?

Best,
Orr
